# -*- coding: utf-8 -*-
"""praktikum2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wcTnmo47vgkgywDllhxW6KKWkBj-nmm
"""

# Praktikum Python Minggu 2

# Print dasar
print("Hello, World!")
print("Hello, Python!")
print("Nama saya Oryza")

# Variabel
nama = "Oryza"
umur = 20
print("Nama:", nama)
print("Umur:", umur)

# Input (Improvisasi)
nama_input = input("Masukkan nama kamu: ")
print("Halo", nama_input)

# Operasi sederhana
a = 5
b = 2
print("Penjumlahan:", a + b)
print("Perkalian:", a * b)

# Formatting
print("Programming","Essentials","in", sep="***", end="...")
print("Python"*2)