# -*- coding: utf-8 -*-
"""praktikum_minggu2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14wcTnmo47vgkgywDllhxW6KKWkBj-nmm
"""

# Praktikum Python Minggu 2

print("Hello World!@#!#!$")
print("Hello, Python!")

nama = "Oryza"
print("Nama:", nama)

# Variabel
Darjo = 3
Darno = 5
Waginem = 6
print("Total apel =", Darjo + Darno + Waginem)

# Operasi
a = 5
b = 2
print("Tambah:", a + b)
print("Kali:", a * b)

# Formatting
print("Programming","Essentials","in", sep="***", end="...")
print("Python"*2)

# Input (improvisasi)
nama_input = input("Masukkan nama: ")
print("Halo", nama_input)